name: Auto Merge PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'Ready to merge')
    runs-on: ubuntu-latest

    steps:
      - name: Check PR approvals
        id: check_approval
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedReviews = reviews.filter(r => r.state === 'APPROVED');
            core.setOutput("approved", approvedReviews.length >= 2);

      - name: Merge Pull Request
        if: steps.check_approval.outputs.approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });
