name: CI Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dummy test
        run: echo "Running tests..." # Ejecutar pruebas reales
