name: Sync develop to main

on:
  schedule:
    - cron: '0 0 * * *' # Ejecución diaria
  workflow_dispatch: # Permite ejecución manual

permissions:
  contents: write

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Asegúrate de clonar todo el historial y todas las ramas

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch and switch to main
        run: |
          git fetch origin main:main # Trae la rama main
          git checkout main          # Haz checkout de la rama main

      - name: Merge develop into main
        run: |
          git merge origin/develop --no-ff

      - name: Push changes to main
        run: |
          git push origin main
