name: Sync develop to main

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: # Permite ejecución manual

permissions:
  contents: write

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Merge develop into main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge develop --no-ff
          git push origin main
