name: Sync Develop to Main

on:
  # schedule:
    # - cron: '0 */4 * * *' # Cada 4 horas (ajusta según tus necesidades)
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

permissions:
  contents: write

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Clona todo el historial y todas las ramas

      - name: Setup Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync Develop to Main
        run: |
          git checkout main
          git pull origin main
          git rebase origin/develop
          git merge origin/develop --no-ff
          git push origin main --force-with-lease
